apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-metrics-api-data
  labels:
    app.kubernetes.io/name: ai-metrics-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
