import os

LOG_PATH = os.getenv("INFERENCE_LOG_PATH", "data/day02/inference.log")
LOG_BACKEND = os.getenv("LOG_BACKEND", "file").lower()
SQLITE_LOG_PATH = os.getenv("SQLITE_LOG_PATH", "data/day02/inference.sqlite3")

DEFAULT_SLOW_THRESHOLD_MS = 200

ALLOWED_FORCE_STATUS_CODES = {200, 400, 429, 500}

SERVICE_ERROR_RATE_WARNING_THRESHOLD = 0.1
SERVICE_ERROR_RATE_CRITICAL_THRESHOLD = 0.2

SERVICE_P95_LATENCY_WARNING_MS = 400
SERVICE_P95_LATENCY_CRITICAL_MS = 800

SERVICE_SLOW_REQUEST_WARNING_COUNT = 3
SERVICE_SLOW_REQUEST_CRITICAL_COUNT = 5

MODEL_ERROR_RATE_WARNING_THRESHOLD = 0.2
MODEL_ERROR_RATE_CRITICAL_THRESHOLD = 0.3

MODEL_P95_LATENCY_WARNING_MS = 400
MODEL_P95_LATENCY_CRITICAL_MS = 800

MODEL_BACKEND = os.getenv("MODEL_BACKEND", "mock").lower()
MOCK_MODEL_SERVER_URL = os.getenv(
    "MOCK_MODEL_SERVER_URL",
    os.getenv("MODEL_SERVER_URL", "http://mock-model-server:8001/generate"),
)
MODEL_SERVER_URL = MOCK_MODEL_SERVER_URL
VLLM_BASE_URL = os.getenv("VLLM_BASE_URL", "http://127.0.0.1:8001/v1").rstrip("/")
VLLM_MODEL = os.getenv("VLLM_MODEL", "Qwen/Qwen2.5-0.5B-Instruct")
MODEL_SERVER_TIMEOUT_SEC = float(
    os.getenv("MODEL_SERVER_TIMEOUT_SEC", os.getenv("MODEL_SERVER_TIMEOUT_SECONDS", "30"))
)
MODEL_SERVER_TIMEOUT_SECONDS = MODEL_SERVER_TIMEOUT_SEC
MAX_IN_FLIGHT_REQUESTS = int(os.getenv("MAX_IN_FLIGHT_REQUESTS", "8"))

ADMISSION_MODE = os.getenv("ADMISSION_MODE", "reject").lower()
MAX_QUEUE_SIZE = int(os.getenv("MAX_QUEUE_SIZE", "32"))
QUEUE_TIMEOUT_MS = int(os.getenv("QUEUE_TIMEOUT_MS", "500"))

REQUIRE_API_KEY = os.getenv("REQUIRE_API_KEY", "false").lower() in {"1", "true", "yes", "on"}
API_KEY = os.getenv("API_KEY", "")

