LOG_PATH = "data/day02/inference.log"

DEFAULT_SLOW_THRESHOLD_MS = 200

ALLOWED_FORCE_STATUS_CODES = {200, 400, 429, 500}

SERVICE_ERROR_RATE_WARNING_THRESHOLD = 0.1
SERVICE_ERROR_RATE_CRITICAL_THRESHOLD = 0.2

SERVICE_P95_LATENCY_WARNING_MS = 400
SERVICE_P95_LATENCY_CRITICAL_MS = 800

SERVICE_SLOW_REQUEST_WARNING_COUNT = 3
SERVICE_SLOW_REQUEST_CRITICAL_COUNT = 5

MODEL_ERROR_RATE_WARNING_THRESHOLD = 0.2
MODEL_ERROR_RATE_CRITICAL_THRESHOLD = 0.3

MODEL_P95_LATENCY_WARNING_MS = 400
MODEL_P95_LATENCY_CRITICAL_MS = 800